### ISSUE TITLE
Crear foro sobre diversidad en tecnología

### ISSUE THREAD

**Issue by dreamingechoes** [folkswhocode/base#10]
Esta issue tiene como finalidad el tratar entre todos uno de los proyectos que la organización quiere llevar a cabo, este es: crear un lugar donde poder generar un foro de debate sobre múltiples temas alrededor de la diversidad en tecnología, y que sea punto de encuentro para todas aquellas personas que tengan inquietudes sobre la misma (ya sea para consultar información, para generar conocimiento, para realizar preguntas sobre un tema concreto...).

Existen varias alternativas para ello: desde crear un foro donde poder registrarse y crear tablones, hilos... (tendría que ser extremadamente sencillo, algo parecido a [elixirforum.com](https://elixirforum.com/)), hasta crear un Slack de la organización donde poder disponer de distintos canales sobre temáticas varias.

¿Cuál es la alternativa que consideráis que encaja mejor? Queda abierto el debate, cualquier idea, aportación u opinión es bienvenida :smile:

**Comment by zapiko** [comment]
El problema de un slack es que si lo que pretendes es que se pueda recurrir (o buscar) información compartida previamente no me parece la mejor erramienta, un elixirforum al estilo [masde140.com](www.masde140.com) me parece la mejor opción

**Comment by IgnaciodeNuevo** [comment]
Me parece una idea muy interesante. Yo creo que las dos opciones más habituales pueden ser Slack (que dudo que se haga mucho uso) o un foro. El foro como dice @zapiko sería fácil para buscar información como links etc. El slack quizá haya gente que no le motive mucho entrar.

Cualquiera de las dos ideas son bienvenidas.

PD.: Gracias por esta iniciativa, me parece genial la idea.

**Comment by jorgegalindocruces** [comment]
Buenas folks,

Personalmente creo que cuanto menos se tire de servicios añadidos a Github mejor, ya que, tienes dependencia de esos servicios y un muro de aprendizaje VS escepticismo de usuarios. 

My two cents sería un canal de chat en Gitter (en base al respositorio de Github). Transparente y de libre acceso y un blog por medio de Markdown en jekyll en el repositorio main, ese blog con comentarios en Disquss. 

Un abrazo!

**Comment by dreamingechoes** [comment]
Una nueva issue ha sido creada en https://github.com/folkswhocode/proposals/issues/2 para continuar debatiendo posibles alternativas, de modo que cierro esta issue 😄
